import { Product } from './products.types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    model: 'iPhone 16',
    brand: 'Apple',
    price_eur: 899.0,
    description:
      'Apple’s mainstream flagship with a brighter OLED display, improved main and ultrawide cameras, and a more efficient chip for better all-day battery life. The chassis is slightly lighter, and the haptics and speakers are class-leading. Ideal for users who want iOS stability without the Pro price.',
    benchmark_score: 92,
    os: 'iOS',
    storage_gb: 128,
    ram_gb: 8,
    stock: 6,
  },
  {
    id: '2',
    model: 'iPhone 16 Plus',
    brand: 'Apple',
    price_eur: 999.0,
    description:
      'Large-screen iPhone with a big battery that comfortably lasts two days for light users. The expansive display is great for media and productivity, while the camera system mirrors the regular iPhone with better thermal headroom under sustained loads.',
    benchmark_score: 93,
    os: 'iOS',
    storage_gb: 128,
    ram_gb: 8,
    stock: 2,
  },
  {
    id: '3',
    model: 'iPhone 16 Pro',
    brand: 'Apple',
    price_eur: 1199.0,
    description:
      'Pro-grade iPhone featuring a high-refresh ProMotion display, a faster next-gen processor, and an advanced 3-lens camera with improved low-light and computational photography. Titanium build keeps it light yet durable; ideal for creators and power users.',
    benchmark_score: 96,
    os: 'iOS',
    storage_gb: 256,
    ram_gb: 8,
    stock: 4,
  },
  {
    id: '4',
    model: 'iPhone 16 Pro Max',
    brand: 'Apple',
    price_eur: 1299.0,
    description:
      'Largest iPhone with the best battery endurance in the lineup and the most capable camera stack, including a long-reach telephoto. The massive screen excels for editing, gaming, and reading, while the premium build and iOS ecosystem deliver long-term value.',
    benchmark_score: 97,
    os: 'iOS',
    storage_gb: 256,
    ram_gb: 8,
    stock: 3,
  },
  {
    id: '5',
    model: 'Galaxy S24',
    brand: 'Samsung',
    price_eur: 899.0,
    description:
      'Compact Android flagship with a bright AMOLED panel, fast flagship chipset, and a versatile triple-camera. One UI adds thoughtful features without getting in the way, and Samsung’s long update policy makes it a safe buy for years.',
    benchmark_score: 90,
    os: 'Android',
    storage_gb: 128,
    ram_gb: 8,
    stock: 5,
  },
  {
    id: '6',
    model: 'Galaxy S24+',
    brand: 'Samsung',
    price_eur: 999.0,
    description:
      'Bigger battery and screen than the S24, ideal for media consumption and multitasking. The cameras are reliable across scenarios, and the phone stays cool under gaming thanks to improved thermals and sustained performance.',
    benchmark_score: 92,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 1,
  },
  {
    id: '7',
    model: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    price_eur: 1299.0,
    description:
      'Samsung’s top-tier device with a superb QHD+ display, S Pen support, and a flagship quad-camera headlined by a high-resolution sensor and long-range zoom. Excellent for productivity, photo/video creators, and power users who want it all.',
    benchmark_score: 95,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 4,
  },
  {
    id: '8',
    model: 'Pixel 9',
    brand: 'Google',
    price_eur: 799.0,
    description:
      'Clean Android with Google’s fastest software updates and powerful on-device AI features. The camera system is consistent and excels at skin tones, while the compact body makes it easy to use one-handed without sacrificing performance.',
    benchmark_score: 89,
    os: 'Android',
    storage_gb: 128,
    ram_gb: 8,
    stock: 7,
  },
  {
    id: '9',
    model: 'Pixel 9 Pro',
    brand: 'Google',
    price_eur: 999.0,
    description:
      'Premium Pixel with a sharper LTPO display and a telephoto lens for lossless portraits and distant subjects. Known for lifelike photos, clean UI, and smart features like call screening and on-device transcription that actually save time.',
    benchmark_score: 92,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 5,
  },
  {
    id: '10',
    model: 'OnePlus 12',
    brand: 'OnePlus',
    price_eur: 849.0,
    description:
      'Fast and fluid flagship with a tuned 120 Hz display, near-stock Android feel, and extremely quick charging. The Hasselblad-branded camera has improved color science, and the battery holds up well even under heavy use.',
    benchmark_score: 91,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 16,
    stock: 8,
  },
  {
    id: '11',
        model: 'OnePlus 12R',
    brand: 'OnePlus',
    price_eur: 599.0,
    description:
      'Value-focused performance phone that brings a flagship-class display and battery life to a lower price point. Great choice for gamers on a budget thanks to sustained performance and fast charging.',
    benchmark_score: 86,
    os: 'Android',
    storage_gb: 128,
    ram_gb: 8,
    stock: 9,
  },
  {
    id: '12',
    model: 'Xiaomi 14',
    brand: 'Xiaomi',
    price_eur: 799.0,
    description:
      'Compact flagship with a bright 1.5K AMOLED, fast charging, and a versatile Leica-tuned camera system. MIUI has matured with smoother animations and strong privacy controls, making this a polished daily driver.',
    benchmark_score: 90,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 7,
  },
  {
    id: '13',
    model: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    price_eur: 1199.0,
    description:
      'Photography-centric flagship with a large-sensor main camera, variable aperture, and excellent manual controls. The build is premium, performance is top-tier, and charging speeds are among the fastest available.',
    benchmark_score: 95,
    os: 'Android',
    storage_gb: 512,
    ram_gb: 16,
    stock: 2,
  },
  {
    id: '14',
    model: 'Xperia 1 VI',
    brand: 'Sony',
    price_eur: 1099.0,
    description:
      'Creator-focused phone with a 4K-class display ratio and pro camera apps that mimic Sony Alpha controls. It’s a niche choice that rewards manual shooting and offers superb video tools, plus a clean Android experience.',
    benchmark_score: 88,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 3,
  },
  {
    id: '15',
    model: 'ROG Phone 8',
    brand: 'ASUS',
    price_eur: 1099.0,
    description:
      'Gaming flagship with an advanced cooling design, high-touch-sampling AMOLED, and shoulder triggers. Massive battery and tuned stereo speakers make it an entertainment beast without sacrificing everyday usability.',
    benchmark_score: 94,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 16,
    stock: 4,
  },
  {
    id: '16',
    model: 'Nothing Phone (2)',
    brand: 'Nothing',
    price_eur: 649.0,
    description:
      'Design-driven device with the unique Glyph interface for glanceable notifications and a clean, fast Android skin. Strong haptics, solid cameras, and a distinctive look make it stand out in the mid-high segment.',
    benchmark_score: 84,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 6,
  },
  {
    id: '17',
    model: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    price_eur: 799.0,
    description:
      'Balanced premium phone with a curved OLED, clean software, and fast charging. Motorola’s Ready For desktop mode adds flexibility, and the cameras are dependable with improved night performance.',
    benchmark_score: 87,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 5,
  },
  {
    id: '18',
    model: 'OPPO Find X7',
    brand: 'OPPO',
    price_eur: 899.0,
    description:
      'Elegant flagship with a high-quality LTPO display and a capable triple-camera tuned for natural tones. ColorOS is smooth and customizable, and battery endurance is strong with very fast wired charging.',
    benchmark_score: 88,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 2,
  },
  {
    id: '19',
    model: 'realme GT 6 Pro',
    brand: 'realme',
    price_eur: 799.0,
    description:
      'Performance-centric phone offering flagship-level speed, a bright display, and rapid charging at a competitive price. The camera is solid for the class, and the phone stays responsive even under heavy multitasking.',
    benchmark_score: 86,
    os: 'Android',
    storage_gb: 256,
    ram_gb: 12,
    stock: 10,
  },
  {
    id: '20',
    model: 'Honor Magic6 Pro',
    brand: 'Honor',
    price_eur: 1199.0,
    description:
      'Premium device with a curved HDR display, long-lasting battery, and a versatile camera system that excels at portraits and zoom. The software is smooth, and Honor’s fast charging and strong signal reception stand out.',
    benchmark_score: 92,
    os: 'Android',
    storage_gb: 512,
    ram_gb: 16,
    stock: 3,
  },
];
